pipeline {
  agent {
    docker {
      image 'maven:3.6.3-jdk-11'
    }
  }
  stages {
    stage('Compilation') {
      steps {
        sh 'mvn package verify'
        junit '**/reports/junit/*.xml'
      }
    }
  }
}
